name: Backend.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install backend dependencies
        working-directory: ./code/backend
        run: npm ci

      - name: Create .env file
        working-directory: ./code/backend
        run: echo "${{ secrets.VESCUEYE_SECRETS }}" > .env

      - name: Reload backend server with pm2
        working-directory: ./code/backend
        run: |
          pm2 reload api || pm2 start server.js --name api
          pm2 save
