name: Backend.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true  # Ensure clean checkout
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Clean npm cache and node_modules
      run: |
        npm cache clean --force
        rm -rf node_modules
        rm -f package-lock.json
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build --if-present
    
    - name: Run tests
      run: npm test --if-present
    
    - name: Setup environment
      run: |
        touch .env
        echo "${{ secrets.VESCUEYE_SECRETS }}" > .env
    
    - name: Restart PM2 (only on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: pm2 restart api
