name: Deploy React Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './code/web-frontend/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./code/web-frontend
        run: npm ci
        
      - name: Build React App
        working-directory: ./code/web-frontend
        run: npm run build
        env:
          CI: false
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: Create remote directory
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo mkdir -p ${{ secrets.REMOTE_APP_PATH }} && sudo chown ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} ${{ secrets.REMOTE_APP_PATH }}"
          
      - name: Deploy to EC2
        run: |
          rsync -avz --delete ./code/web-frontend/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.REMOTE_APP_PATH }}/
          
      - name: Verify deployment
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "ls -la ${{ secrets.REMOTE_APP_PATH }}"
