name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm ci

    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.VESCUEYE_SECRETS }}" > .env

    - name: Build React app
      run: npm run build

    - name: Move build to web root
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -r build/* /var/www/html/
