name: NodeT.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      # Write the secrets to .env securely
      - name: Create .env file from secrets
        run: |
          echo "${{ secrets.VESCUEYE_SECRETS }}" > .env
        working-directory: ./code/backend

      # Restart your API with pm2
      - name: Restart API with pm2
        run: pm2 restart api
        working-directory: ./code/backend
