name: Frontend CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./code/web-frontend
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'code/web-frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
      timeout-minutes: 10
      env:
        NODE_ENV: production
        NODE_OPTIONS: --max_old_space_size=4096
        GENERATE_SOURCEMAP: false
        CI: false  # Disable treating warnings as errors
    
    - name: Deploy to nginx directory
      run: |
        sudo rm -rf /var/www/frontend/*
        sudo cp -r build/* /var/www/frontend/
        sudo chown -R www-data:www-data /var/www/frontend
        sudo systemctl reload nginx
    
    - name: Verify deployment
      run: |
        echo "Deployed files:"
        sudo ls -la /var/www/frontend/
