name: Frontend CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Use GitHub's runners for heavy lifting
    defaults:
      run:
        working-directory: ./code/web-frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: 'code/web-frontend/package-lock.json'
      
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      
      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          GENERATE_SOURCEMAP: false
          CI: false
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: code/web-frontend/build/
          retention-days: 1

  deploy:
    needs: build
    runs-on: self-hosted # Use your EC2 only for deployment
    timeout-minutes: 5
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./build
      
      - name: Create nginx directory if it doesn't exist
        run: |
          sudo mkdir -p /var/www/frontend/
          echo "Directory created/verified"
      
      - name: Deploy to nginx directory
        run: |
          # Clear existing files (only if directory exists and has content)
          if [ -d "/var/www/frontend" ] && [ "$(ls -A /var/www/frontend/)" ]; then
            sudo rm -rf /var/www/frontend/*
            echo "Cleared existing files"
          fi
          
          # Copy new files
          sudo cp -r ./build/* /var/www/frontend/
          echo "Files copied successfully"
          
          # Set proper ownership
          sudo chown -R www-data:www-data /var/www/frontend
          echo "Ownership set"
          
          # Reload nginx
          sudo systemctl reload nginx
          echo "Nginx reloaded"
      
      - name: Verify deployment
        run: |
          echo "Deployed files:"
          sudo ls -la /var/www/frontend/
          echo "Deployment verification complete"
      
      - name: Cleanup
        run: |
          rm -rf ./build
          echo "Cleanup completed"
